/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p bluezadapter bluez-adapter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "bluezadapter.h"

/*
 * Implementation of interface class OrgBluezAdapterInterface
 */

OrgBluezAdapterInterface::OrgBluezAdapterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezAdapterInterface::~OrgBluezAdapterInterface()
{
}

/*
 * Implementation of interface class OrgBluezNetworkHubInterface
 */

OrgBluezNetworkHubInterface::OrgBluezNetworkHubInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezNetworkHubInterface::~OrgBluezNetworkHubInterface()
{
}

/*
 * Implementation of interface class OrgBluezNetworkPeerInterface
 */

OrgBluezNetworkPeerInterface::OrgBluezNetworkPeerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezNetworkPeerInterface::~OrgBluezNetworkPeerInterface()
{
}

/*
 * Implementation of interface class OrgBluezNetworkRouterInterface
 */

OrgBluezNetworkRouterInterface::OrgBluezNetworkRouterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezNetworkRouterInterface::~OrgBluezNetworkRouterInterface()
{
}

/*
 * Implementation of interface class OrgBluezSerialProxyManagerInterface
 */

OrgBluezSerialProxyManagerInterface::OrgBluezSerialProxyManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezSerialProxyManagerInterface::~OrgBluezSerialProxyManagerInterface()
{
}

/*
 * Implementation of interface class OrgBluezServiceInterface
 */

OrgBluezServiceInterface::OrgBluezServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezServiceInterface::~OrgBluezServiceInterface()
{
}
