######################################################################
# Automatically generated by qmake (2.01a) gio set 9 14:28:11 2010
######################################################################

TEMPLATE = app
TARGET = 

QT -= gui
CONFIG += debug warn_on

# Input
SOURCES += main.cpp
