######################################################################
# Automatically generated by qmake (2.01a) mer set 8 16:33:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
